# Generated by Django 3.1.1 on 2020-11-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkatdcu', '0002_auto_20201108_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carpark',
            new_name='Car',
        ),
    ]
