# Generated by Django 3.1.2 on 2020-11-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkatdcu', '0004_auto_20201108_2215'),
        ('parkatdcu', '0002_auto_20201029_1652'),
    ]

    operations = [
    ]
