# Generated by Django 3.1.2 on 2020-11-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkatdcu', '0005_merge_20201118_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='campus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkatdcu.campus'),
        ),
    ]
